// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using ParksLookup.Models;

namespace ParksLookup.Migrations
{
    [DbContext(typeof(ParksLookupContext))]
    partial class ParksLookupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksLookup.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Local")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("National")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ParkLocation")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ParkName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Local = true,
                            National = false,
                            ParkLocation = "Portland, OR",
                            ParkName = "Buike"
                        },
                        new
                        {
                            ParkId = 2,
                            Local = false,
                            National = true,
                            ParkLocation = "Sierra Nevada, CA",
                            ParkName = "Yosemite"
                        },
                        new
                        {
                            ParkId = 3,
                            Local = true,
                            National = false,
                            ParkLocation = "Denver, CO",
                            ParkName = "LakeView"
                        },
                        new
                        {
                            ParkId = 4,
                            Local = false,
                            National = true,
                            ParkLocation = "Arizona",
                            ParkName = "Grand Canyon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
